/*
//
// National TeleConsultants LLC
//
//  This product includes software developed at
//  National TeleConsultants LLC
//  550 North Brand Blvd
//  17th Floor
//  Glendale, CA 91203-1944  USA
//
//  Web:        http://www.ntc.com
//
// Project: N3968-A
// Module:  DINGOSDB database creation script.
// Created: 2013-Oct-23
// Author:  Tony Lew
// 
// Purpose: Database creation only.
//    
//
//   Current revision:
//     Release:   2.0
//     Revision:  $Id: DBCreationScript.sql 3070 2013-11-14 01:26:29Z nbrownett $
//    
//
*/ 

USE [MASTER]
GO
/****** OBJECT:  DATABASE [DINGOSDB]    SCRIPT DATE: 09/17/2013 11:44:27 ******/
CREATE DATABASE [DINGOSDB] ON  PRIMARY 
( NAME = N'DINGOSDB', FILENAME = N'D:\DATA\DINGOSDB.MDF' , SIZE = 100MB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DINGOSDB_LOG', FILENAME = N'D:\LOG\DINGOSDB.LDF' , SIZE = 100MB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [DINGOSDB] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('ISFULLTEXTINSTALLED'))
BEGIN
EXEC [DINGOSDB].[DBO].[SP_FULLTEXT_DATABASE] @ACTION = 'ENABLE'
END
GO
ALTER DATABASE [DINGOSDB] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [DINGOSDB] SET ANSI_NULLS OFF
GO
ALTER DATABASE [DINGOSDB] SET ANSI_PADDING OFF
GO
ALTER DATABASE [DINGOSDB] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [DINGOSDB] SET ARITHABORT OFF
GO
ALTER DATABASE [DINGOSDB] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [DINGOSDB] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [DINGOSDB] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [DINGOSDB] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [DINGOSDB] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [DINGOSDB] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [DINGOSDB] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [DINGOSDB] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [DINGOSDB] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [DINGOSDB] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [DINGOSDB] SET  ENABLE_BROKER
GO
ALTER DATABASE [DINGOSDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [DINGOSDB] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [DINGOSDB] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [DINGOSDB] SET ALLOW_SNAPSHOT_ISOLATION ON
GO
ALTER DATABASE [DINGOSDB] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [DINGOSDB] SET READ_COMMITTED_SNAPSHOT ON
GO
ALTER DATABASE [DINGOSDB] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [DINGOSDB] SET  READ_WRITE
GO
ALTER DATABASE [DINGOSDB] SET RECOVERY FULL
GO
ALTER DATABASE [DINGOSDB] SET  MULTI_USER
GO
ALTER DATABASE [DINGOSDB] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [DINGOSDB] SET DB_CHAINING OFF
GO


ALTER DATABASE TempDB MODIFY FILE
(NAME = tempdev, FILENAME = 'D:\TempDB\tempdb.mdf')
GO
ALTER DATABASE TempDB MODIFY FILE
(NAME = templog, FILENAME = 'D:\TempDB\templog.ldf')
GO



