/*
//
// National TeleConsultants LLC
//
//  This product includes software developed at
//  National TeleConsultants LLC
//  550 North Brand Blvd
//  17th Floor
//  Glendale, CA 91203-1944  USA
//
//  Web:        http://www.ntc.com
//
// Project: N3968-A
// Module:  dbo.REGIONALIZED_ZONE
// Created: 2013-Oct-23
// Author:  Tony Lew
// 
// Purpose: Regionalizes Seachange zones
//    
//
//   Current revision:
//     Release:   2.0
//     Revision:  $Id: DINGODB.dbo.REGIONALIZED_ZONE.table.sql 3650 2014-03-10 17:33:42Z tlew $
//    
//
*/ 


USE [DINGODB]
GO


CREATE TABLE [dbo].[REGIONALIZED_ZONE](
	[REGIONALIZED_ZONE_ID] [int] IDENTITY(1,1) NOT NULL,
	[REGION_ID] [int] NOT NULL,
	[ZONE_MAP_ID] [int] NULL,
	[ZONE_ID] [int] NOT NULL,
	[ZONE_NAME] [varchar](32) NOT NULL,
	[DATABASE_SERVER_NAME] [varchar](32) NOT NULL,
	[DB_ID] [int] NULL,
	[SCHEDULE_RELOADED] [int] NOT NULL,
	[MAX_DAYS] [int] NULL,
	[MAX_ROWS] [int] NULL,
	[TB_TYPE] [int] NULL,
	[LOAD_TTL] [int] NULL,
	[LOAD_TOD] [datetime] NULL,
	[ASRUN_TTL] [int] NULL,
	[ASRUN_TOD] [datetime] NULL,
	[IC_ZONE_ID] [int] NULL,
	[PRIMARY_BREAK] [int] NULL,
	[SECONDARY_BREAK] [int] NULL,
	[msrepl_tran_version] [uniqueidentifier] NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[UpdateDate] [datetime] NOT NULL,
 CONSTRAINT [PK_REGIONALIZED_ZONE] PRIMARY KEY CLUSTERED 
(
	[REGIONALIZED_ZONE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'DINGODB regionalized unique identifier' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REGIONALIZED_ZONE', @level2type=N'COLUMN',@level2name=N'REGIONALIZED_ZONE_ID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'SPOT region id' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REGIONALIZED_ZONE', @level2type=N'COLUMN',@level2name=N'REGION_ID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'SPOT zone id' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REGIONALIZED_ZONE', @level2type=N'COLUMN',@level2name=N'ZONE_ID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'SPOT zone name' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REGIONALIZED_ZONE', @level2type=N'COLUMN',@level2name=N'ZONE_NAME'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'A unique identifier that is system generated and that will change when the row changes to indicate an update is necessary' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REGIONALIZED_ZONE', @level2type=N'COLUMN',@level2name=N'msrepl_tran_version'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'UTC date and time this row was created' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REGIONALIZED_ZONE', @level2type=N'COLUMN',@level2name=N'CreateDate'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'UTC date and time this row was last updated' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REGIONALIZED_ZONE', @level2type=N'COLUMN',@level2name=N'UpdateDate'
GO


ALTER TABLE [dbo].[REGIONALIZED_ZONE]  WITH CHECK ADD  CONSTRAINT [FK_REGIONALIZED_ZONE_Region_ID_-->_Region_RegionID] FOREIGN KEY([Region_ID])
REFERENCES [dbo].[Region] ([RegionID])
GO

ALTER TABLE [dbo].[REGIONALIZED_ZONE] CHECK CONSTRAINT [FK_REGIONALIZED_ZONE_Region_ID_-->_Region_RegionID]
GO


--ALTER TABLE [dbo].[REGIONALIZED_ZONE]  WITH CHECK ADD  CONSTRAINT [FK_REGIONALIZED_ZONE_ZONE_MAP_ID_-->_ZONE_MAP_ZONE_MAP_ID] FOREIGN KEY([ZONE_MAP_ID])
--REFERENCES [dbo].[ZONE_MAP] ([ZONE_MAP_ID])
--GO

--ALTER TABLE [dbo].[REGIONALIZED_ZONE] CHECK CONSTRAINT [FK_REGIONALIZED_ZONE_ZONE_MAP_ID_-->_ZONE_MAP_ZONE_MAP_ID]
--GO


ALTER TABLE [dbo].[REGIONALIZED_ZONE] ADD  CONSTRAINT [DF_REGIONALIZED_ZONE_CreateDate]  DEFAULT (getutcdate()) FOR [CreateDate]
GO

ALTER TABLE [dbo].[REGIONALIZED_ZONE] ADD  CONSTRAINT [DF_REGIONALIZED_ZONE_UpdateDate]  DEFAULT (getutcdate()) FOR [UpdateDate]
GO



--DROP INDEX dbo.REGIONALIZED_ZONE.UNC_REGIONALIZED_ZONE_ZONE_NAME_iREGION_ID_msrepl_tran_version
--CREATE UNIQUE INDEX UNC_REGIONALIZED_ZONE_ZONE_NAME_iREGION_ID_msrepl_tran_version ON dbo.REGIONALIZED_ZONE ( ZONE_NAME ) INCLUDE ( REGION_ID, msrepl_tran_version )
--GO


CREATE INDEX UNC_REGIONALIZED_ZONE_ZONE_NAME_DATABASE_SERVER_NAME_imsrepl_tran_version ON dbo.REGIONALIZED_ZONE ( ZONE_NAME, DATABASE_SERVER_NAME ) INCLUDE ( msrepl_tran_version )
GO


CREATE UNIQUE INDEX UNC_REGIONALIZED_ZONE_ZONE_NAME_REGION_ID_imsrepl_tran_version ON dbo.REGIONALIZED_ZONE ( ZONE_NAME, REGION_ID ) INCLUDE ( msrepl_tran_version )
GO

--select * from dbo.REGIONALIZED_ZONE  
--alter table dbo.REGIONALIZED_ZONE  alter column ZONE_MAP_ID INT NOT NULL
--Update dbo.REGIONALIZED_ZONE 
--set ZONE_MAP_ID = x.ZONE_MAP_ID
--from dbo.ZONE_MAP x
--WHERE REGIONALIZED_ZONE.ZONE_NAME = x.dbo.REGIONALIZED_ZONE 


------Truncate Table dbo.REGIONALIZED_ZONE
------DELETE dbo.REGIONALIZED_ZONE 
--DECLARE @RegionID INT = 1
INSERT dbo.REGIONALIZED_ZONE 
			( 
				REGION_ID,
				ZONE_ID,
				ZONE_NAME,
				ZONE_MAP_ID,
				DATABASE_SERVER_NAME,
				SCHEDULE_RELOADED,
				msrepl_tran_version,
				CreateDate, 
				UpdateDate 
			)
SELECT 			
				x.REGION_ID,
				w.ZONE_MAP_ID,
				x.ZONE_ID,
				x.ZONE_NAME,
				x.DATABASE_SERVER_NAME,
				x.SCHEDULE_RELOADED,
				x.msrepl_tran_version,
				GETUTCDATE() AS CreateDate, 
				GETUTCDATE() AS UpdateDate
FROM (
			select 
							1 AS REGION_ID,
							ZONE_ID,
							ZONE_NAME,
							DATABASE_SERVER_NAME,
							SCHEDULE_RELOADED,
							msrepl_tran_version
			from MSSNKNLMDB001P.mpeg.dbo.ZONE WITH (NOLOCK) UNION ALL
			select 
							2 AS REGION_ID,
							ZONE_ID,
							ZONE_NAME,
							DATABASE_SERVER_NAME,
							SCHEDULE_RELOADED,
							msrepl_tran_version
			from MSSNTC4MDB001P.mpeg.dbo.ZONE WITH (NOLOCK) 
	) x
left join dbo.ZONE_MAP w
ON x.ZONE_NAME = w.ZONE_NAME
left join dbo.REGIONALIZED_ZONE y
ON x.REGION_ID = y.REGION_ID
AND x.ZONE_ID = y.ZONE_ID
where y.REGIONALIZED_ZONE_ID IS NULL
Order by x.REGION_ID, x.ZONE_ID

select * from dbo.REGIONALIZED_ZONE



		--SELECT 2 AS REGIONALIZED_ZONE_ID, 	0	AS ZONE_ID, '*** MASTER ***' AS ZONE_NAME, 	0 AS MARKETID,  0 AS ICPROVIDERID,  0 AS ROCID UNION		--N/A	N/A	N/A
		--SELECT 3 AS REGIONALIZED_ZONE_ID, 	2	AS ZONE_ID, 'LRCSNTX' AS ZONE_NAME,			1 AS MARKETID,  1 AS ICPROVIDERID,  2 AS ROCID UNION		--RCSNTX	TIME-WARNER	TWC (D)
		--SELECT 4 AS REGIONALIZED_ZONE_ID, 	5	AS ZONE_ID, 'LDETROIT' AS ZONE_NAME,		2 AS MARKETID,  0 AS ICPROVIDERID,  1 AS ROCID UNION		--LIVNMI	COMCAST	CC
		--SELECT 5 AS REGIONALIZED_ZONE_ID, 	7	AS ZONE_ID, 'LTUKRGV' AS ZONE_NAME,			3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--TUKRGV	COMCAST	CC
		--SELECT 6 AS REGIONALIZED_ZONE_ID, 	11	AS ZONE_ID, 'LMIAMIFL' AS ZONE_NAME,		4 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--MIAMFL	COMCAST	CC
		--SELECT 7 AS REGIONALIZED_ZONE_ID, 	99	AS ZONE_ID, 'INTERNAL ZONE' AS ZONE_NAME,	0 AS MARKETID,  0 AS ICPROVIDERID,  0 AS ROCID UNION		--N/A	N/A	N/A
		--SELECT 8 AS REGIONALIZED_ZONE_ID, 	107	AS ZONE_ID, 'ATLANTA' AS ZONE_NAME,			3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--TUKRGV	COMCAST	CC
		--SELECT 9 AS REGIONALIZED_ZONE_ID, 	111	AS ZONE_ID, 'MIAMI' AS ZONE_NAME,			4 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--MIAMFL	COMCAST	CC
		--SELECT 10 AS REGIONALIZED_ZONE_ID,	170	AS ZONE_ID, 'TUKRGV-00701' AS ZONE_NAME,	3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--TUKRGV	COMCAST	CC
		--SELECT 11 AS REGIONALIZED_ZONE_ID,	171	AS ZONE_ID, 'TUKRGV-00702' AS ZONE_NAME,	3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--TUKRGV	COMCAST	CC
		--SELECT 12 AS REGIONALIZED_ZONE_ID,	172	AS ZONE_ID, 'TUKRGV-00703' AS ZONE_NAME,	3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--TUKRGV	COMCAST	CC
		--SELECT 13 AS REGIONALIZED_ZONE_ID,	173	AS ZONE_ID, 'TUKRGV-00704' AS ZONE_NAME,	3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--TUKRGV	COMCAST	CC
		--SELECT 14 AS REGIONALIZED_ZONE_ID,	174	AS ZONE_ID, 'TUKRGV-00705' AS ZONE_NAME,	3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--TUKRGV	COMCAST	CC
		--SELECT 15 AS REGIONALIZED_ZONE_ID,	175	AS ZONE_ID, 'TUKRGV-00706' AS ZONE_NAME,	3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--TUKRGV	COMCAST	CC
		--SELECT 16 AS REGIONALIZED_ZONE_ID,	176	AS ZONE_ID, 'TUKRGV-00707' AS ZONE_NAME,	3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--TUKRGV	COMCAST	CC
		--SELECT 17 AS REGIONALIZED_ZONE_ID,	177	AS ZONE_ID, 'TUKRGV-00708' AS ZONE_NAME,	3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--TUKRGV	COMCAST	CC
		--SELECT 18 AS REGIONALIZED_ZONE_ID,	178	AS ZONE_ID, 'TUKRGV-00709' AS ZONE_NAME,	3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--TUKRGV	COMCAST	CC
		--SELECT 19 AS REGIONALIZED_ZONE_ID,	179	AS ZONE_ID, 'TUKRGV-00710' AS ZONE_NAME,	3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--TUKRGV	COMCAST	CC
		--SELECT 20 AS REGIONALIZED_ZONE_ID,	180	AS ZONE_ID, 'TUKRGV-00711' AS ZONE_NAME,	3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--TUKRGV	COMCAST	CC
		--SELECT 21 AS REGIONALIZED_ZONE_ID,	181	AS ZONE_ID, 'TUKRGV-00712' AS ZONE_NAME,	3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--TUKRGV	COMCAST	CC
		--SELECT 22 AS REGIONALIZED_ZONE_ID,	182	AS ZONE_ID, 'TUKRGV-00713' AS ZONE_NAME,	3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--TUKRGV	COMCAST	CC
		--SELECT 23 AS REGIONALIZED_ZONE_ID,	183	AS ZONE_ID, 'TUKRGV-00714' AS ZONE_NAME,	3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--TUKRGV	COMCAST	CC
		--SELECT 24 AS REGIONALIZED_ZONE_ID,	184	AS ZONE_ID, 'TUKRGV-00715' AS ZONE_NAME,	3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--TUKRGV	COMCAST	CC
		--SELECT 25 AS REGIONALIZED_ZONE_ID,	185	AS ZONE_ID, 'TUKRGV-00716' AS ZONE_NAME,	3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--TUKRGV	COMCAST	CC
		--SELECT 26 AS REGIONALIZED_ZONE_ID,	186	AS ZONE_ID, 'TUKRGV-00717' AS ZONE_NAME,	3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--TUKRGV	COMCAST	CC
		--SELECT 27 AS REGIONALIZED_ZONE_ID,	187	AS ZONE_ID, 'TUKRGV-00718' AS ZONE_NAME,	3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--TUKRGV	COMCAST	CC
		--SELECT 28 AS REGIONALIZED_ZONE_ID,	188	AS ZONE_ID, 'TUKRGV-00719' AS ZONE_NAME,	3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--TUKRGV	COMCAST	CC
		--SELECT 29 AS REGIONALIZED_ZONE_ID,	189	AS ZONE_ID, 'TUKRGV-00720' AS ZONE_NAME,	3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID UNION		--TUKRGV	COMCAST	CC
		--SELECT 30 AS REGIONALIZED_ZONE_ID,	570	AS ZONE_ID, 'RCSNTX-00201' AS ZONE_NAME,	1 AS MARKETID,  1 AS ICPROVIDERID,  2 AS ROCID UNION		--RCSNTX	TIME-WARNER	TWC (D)
		--SELECT 31 AS REGIONALIZED_ZONE_ID,	571	AS ZONE_ID, 'RCSNTX-00202' AS ZONE_NAME,	1 AS MARKETID,  1 AS ICPROVIDERID,  2 AS ROCID UNION		--RCSNTX	TIME-WARNER	TWC (D)
		--SELECT 32 AS REGIONALIZED_ZONE_ID,	572	AS ZONE_ID, 'RCSNTX-00203' AS ZONE_NAME,	1 AS MARKETID,  1 AS ICPROVIDERID,  2 AS ROCID UNION		--RCSNTX	TIME-WARNER	TWC (D)
		--SELECT 33 AS REGIONALIZED_ZONE_ID,	573	AS ZONE_ID, 'RCSNTX-00204' AS ZONE_NAME,	1 AS MARKETID,  1 AS ICPROVIDERID,  2 AS ROCID UNION		--RCSNTX	TIME-WARNER	TWC (D)
		--SELECT 34 AS REGIONALIZED_ZONE_ID,	574	AS ZONE_ID, 'RCSNTX-00205' AS ZONE_NAME,	1 AS MARKETID,  1 AS ICPROVIDERID,  2 AS ROCID UNION		--RCSNTX	TIME-WARNER	TWC (D)
		--SELECT 35 AS REGIONALIZED_ZONE_ID,	575	AS ZONE_ID, 'RCSNTX-00206' AS ZONE_NAME,	1 AS MARKETID,  1 AS ICPROVIDERID,  2 AS ROCID UNION		--RCSNTX	TIME-WARNER	TWC (D)
		--SELECT 36 AS REGIONALIZED_ZONE_ID,	576	AS ZONE_ID, 'RCSNTX-00207' AS ZONE_NAME,	1 AS MARKETID,  1 AS ICPROVIDERID,  2 AS ROCID UNION		--RCSNTX	TIME-WARNER	TWC (D)
		--SELECT 37 AS REGIONALIZED_ZONE_ID,	577	AS ZONE_ID, 'RCSNTX-00208' AS ZONE_NAME,	1 AS MARKETID,  1 AS ICPROVIDERID,  2 AS ROCID UNION		--RCSNTX	TIME-WARNER	TWC (D)
		--SELECT 38 AS REGIONALIZED_ZONE_ID,	578	AS ZONE_ID, 'RCSNTX-00209' AS ZONE_NAME,	1 AS MARKETID,  1 AS ICPROVIDERID,  2 AS ROCID UNION		--RCSNTX	TIME-WARNER	TWC (D)
		--SELECT 39 AS REGIONALIZED_ZONE_ID,	579	AS ZONE_ID, 'RCSNTX-00210' AS ZONE_NAME,	1 AS MARKETID,  1 AS ICPROVIDERID,  2 AS ROCID UNION		--RCSNTX	TIME-WARNER	TWC (D)
		--SELECT 40 AS REGIONALIZED_ZONE_ID,	580	AS ZONE_ID, 'RCSNTX-00211' AS ZONE_NAME,	1 AS MARKETID,  1 AS ICPROVIDERID,  2 AS ROCID UNION		--RCSNTX	TIME-WARNER	TWC (D)
		--SELECT 41 AS REGIONALIZED_ZONE_ID,	581	AS ZONE_ID, 'RCSNTX-00212' AS ZONE_NAME,	1 AS MARKETID,  1 AS ICPROVIDERID,  2 AS ROCID UNION		--RCSNTX	TIME-WARNER	TWC (D)
		--SELECT 42 AS REGIONALIZED_ZONE_ID,	582	AS ZONE_ID, 'RCSNTX-00213' AS ZONE_NAME,	1 AS MARKETID,  1 AS ICPROVIDERID,  2 AS ROCID UNION		--RCSNTX	TIME-WARNER	TWC (D)
		--SELECT 43 AS REGIONALIZED_ZONE_ID,	583	AS ZONE_ID, 'RCSNTX-00214' AS ZONE_NAME,	1 AS MARKETID,  1 AS ICPROVIDERID,  2 AS ROCID UNION		--RCSNTX	TIME-WARNER	TWC (D)
		--SELECT 44 AS REGIONALIZED_ZONE_ID,	584	AS ZONE_ID, 'RCSNTX-00215' AS ZONE_NAME,	1 AS MARKETID,  1 AS ICPROVIDERID,  2 AS ROCID UNION		--RCSNTX	TIME-WARNER	TWC (D)
		--SELECT 45 AS REGIONALIZED_ZONE_ID,	585	AS ZONE_ID, 'RCSNTX-00216' AS ZONE_NAME,	1 AS MARKETID,  1 AS ICPROVIDERID,  2 AS ROCID UNION		--RCSNTX	TIME-WARNER	TWC (D)
		--SELECT 46 AS REGIONALIZED_ZONE_ID,	967	AS ZONE_ID, 'ATLANTA_NAI' AS ZONE_NAME,		3 AS MARKETID,  2 AS ICPROVIDERID,  1 AS ROCID 				--TUKRGV	COMCAST	CC


