USE [master]
GO

/****** Object:  Database [RDDB]    Script Date: 2016-12-02 23:22:15 ******/
CREATE DATABASE [RDDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RDDB', FILENAME = N'D:\SQLData\RDDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RDDB_log', FILENAME = N'D:\SQLLog\RDDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [RDDB] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RDDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RDDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RDDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RDDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RDDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RDDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [RDDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RDDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RDDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RDDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RDDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RDDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RDDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RDDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RDDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RDDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RDDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RDDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RDDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RDDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RDDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RDDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RDDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RDDB] SET RECOVERY FULL 
GO

ALTER DATABASE [RDDB] SET  MULTI_USER 
GO

ALTER DATABASE [RDDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RDDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RDDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RDDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RDDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RDDB] SET QUERY_STORE = OFF
GO

USE [RDDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

USE [RDDB]
GO

EXEC [RDDB].sys.sp_addextendedproperty @name=N'pdw_tempdb_physical_name', @value=N'pdwtempdb1' 
GO

USE [master]
GO

ALTER DATABASE [RDDB] SET  READ_WRITE 
GO


